volumes:
  build:

services:
  cosmetology-server:
    image: dahakalab/cosmetology-backend:latest
    container_name: cosmetology-server
    restart: always
    ports:
      - 3000:3000

  cosmetology-user-app:
    depends_on:
      - cosmetology-server
    build:
      dockerfile: Dockerfile
    container_name: cosmetology-user-app
    volumes:
      - build:/app/build

  cosmetology-web-server:
    depends_on:
      - cosmetology-user-app
    image: nginx:alpine
    container_name: cosmetology-client-server
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - build:/usr/share/nginx/html:ro
