name: Prepare

inputs:
  ssh-key:
    required: true
    description: SSH private key for accessing GitHub repos

runs:
  using: "composite"
  steps:
    - name: Set up SSH for GitHub
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Start SSH agent and add key
      shell: bash
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
