name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/template/prepare
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        uses: ./.github/template/build
      - name: Lint
        run: npm run lint
      - name: Lint CSS
        run: npm run lintcss

  build:
    needs: lint
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       github.base_ref == 'main')
    runs-on: self-hosted
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare
        uses: ./.github/template/prepare
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: dahakalab/cosmetology-user-app:latest
          ssh: default